

name: armTemplateDeployment

on:
  push:
    branches:
      - main 
  workflow_dispatch:


jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 08335517-f87b-4ad8-ab7b-64a80313767b
          region: UK South
          template: .github/workflows/arm-templates/resourcegroup.json
          parameters:
            location=UK South
            resourceGroupName:rg-githubactions
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy # ID used to identify a work flow task
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: 08335517-f87b-4ad8-ab7b-64a80313767b
          region: UK South
          template: .github/workflows/arm-templates/storageaccount.json
          parameters: 
            #.github/workflows/arm-templates/storageaccount.parameters.json
              sku=Standard_LRS
              storageAccountName=globostgtn002
              location="UK South"
          deploymentMode: incremental

      - run: echo ${{steps.storageAccountDeploy.outputs.BlobUri}}



    # inline Azure CLI 
    #  - name: Deploy Resource Group rg-githubactions with AZ CLI
    #    uses: Azure/cli@v1
    #    with:
    #        inlinescript: |
    #         az deployment sub create --location "UK South" --template-file .github/workflows/arm-templates/resourcegroup.json

